### ISSUE TITLE
THIS SHIT IS COOL, how do I use this?

### ISSUE THREAD

**Issue by CertifiedRice** [glaukiol1/auto-commit#1]
How do I set this up?

**Comment by CertifiedRice** [comment]
Never mind lol

**Comment by glaukiol1** [comment]
u figured it out?

**Comment by glaukiol1** [comment]
you run it with Go

**Comment by CertifiedRice** [comment]
yes lol, I replaced the .mod file with my repo then do `go run main.go`
You prob noticed the huge ass spike in my contributions graph XD

**Comment by glaukiol1** [comment]
Go check out my new repo; top-github-commiters. It gives the top commiters for every country. You can follow the instructions on the readme!

**Comment by CertifiedRice** [comment]
ok
